# Generated by Django 5.1.15 on 2026-06-12 19:52

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("talla", models.CharField(max_length=10)),
                ("color", models.CharField(max_length=120)),
                ("detalles", models.CharField(blank=True, max_length=255)),
                ("marca", models.CharField(blank=True, max_length=120)),
                ("saco", models.CharField(blank=True, max_length=80)),
                ("chaleco", models.CharField(blank=True, max_length=80)),
                ("pantalon", models.CharField(blank=True, max_length=80)),
                ("codigo_old", models.CharField(blank=True, max_length=80)),
                ("codigo_new", models.CharField(blank=True, max_length=80)),
                (
                    "estatus",
                    models.CharField(
                        choices=[
                            ("rentado", "Rentado"),
                            ("disponible", "Disponible"),
                            ("mantenimiento", "Mantenimiento"),
                        ],
                        default="disponible",
                        max_length=20,
                    ),
                ),
                ("ubicacion", models.CharField(blank=True, max_length=120)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "prenda",
                "verbose_name_plural": "prendas",
                "ordering": ["codigo_new", "talla", "color"],
            },
        ),
        migrations.CreateModel(
            name="Renta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.JSONField(default=api.models.celda_vacia)),
                ("saco", models.JSONField(default=api.models.celda_vacia)),
                ("chaleco", models.JSONField(default=api.models.celda_vacia)),
                ("pantalon", models.JSONField(default=api.models.celda_vacia)),
                ("camisa", models.JSONField(default=api.models.celda_vacia)),
                ("corbata_mono", models.JSONField(default=api.models.celda_vacia)),
                ("cinto", models.JSONField(default=api.models.celda_vacia)),
                ("accesorio", models.JSONField(default=api.models.celda_vacia)),
                (
                    "tipo_entrega",
                    models.CharField(
                        choices=[("recoger", "Recoger"), ("premier", "Premier")],
                        default="recoger",
                        max_length=10,
                    ),
                ),
                ("empleado", models.JSONField(default=api.models.celda_vacia)),
                ("cliente", models.JSONField(default=api.models.celda_vacia)),
                ("fecha_cita", models.JSONField(default=api.models.celda_vacia)),
                ("horario", models.JSONField(default=api.models.celda_vacia)),
                ("detalles", models.JSONField(default=api.models.celda_vacia)),
                (
                    "estatus_fila",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("normal", "Normal"),
                            ("salio", "Salió"),
                            ("sucio", "Sucio"),
                            ("mojado", "Mojado"),
                            ("en_ajustes", "En ajustes"),
                            ("listo_para_entregar", "Listo para entregar"),
                        ],
                        max_length=24,
                    ),
                ),
                ("semana_inicio", models.DateField()),
                ("fecha_salida", models.CharField(max_length=32)),
                ("fecha_regreso", models.CharField(max_length=32)),
                (
                    "fondo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "multa",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "renta",
                "verbose_name_plural": "rentas",
                "ordering": ["-semana_inicio", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Transaccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("referencia", models.CharField(max_length=80, unique=True)),
                ("cliente", models.CharField(max_length=200)),
                (
                    "pago",
                    models.CharField(
                        choices=[
                            ("Efectivo", "Efectivo"),
                            ("Tarjeta", "Tarjeta"),
                            ("Transferencia", "Transferencia"),
                        ],
                        max_length=20,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "transacción",
                "verbose_name_plural": "transacciones",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Devolucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cliente", models.CharField(max_length=200)),
                ("prenda_nombre", models.CharField(max_length=200)),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "estatus",
                    models.CharField(
                        choices=[
                            ("salio", "Salió"),
                            ("listo_para_entregar", "Listo para entregar"),
                            ("mojado", "Mojado"),
                            ("en_ajustes", "En ajustes"),
                            ("sucio", "Sucio"),
                            ("retrasado", "Retrasado"),
                        ],
                        max_length=24,
                    ),
                ),
                ("fecha_limite", models.DateField()),
                (
                    "penalizacion",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "prenda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devoluciones",
                        to="api.prenda",
                    ),
                ),
                (
                    "renta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devoluciones",
                        to="api.renta",
                    ),
                ),
            ],
            options={
                "verbose_name": "devolución",
                "verbose_name_plural": "devoluciones",
                "ordering": ["fecha_limite", "-id"],
            },
        ),
    ]
