# Generated by Django 5.1.15 on 2026-06-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="renta",
            name="direccion",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="renta",
            name="telefono",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
