# Generated by Django 5.1.15 on 2026-06-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_renta_telefono_direccion"),
    ]

    operations = [
        migrations.AddField(
            model_name="renta",
            name="anticipo",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
