# Generated by Django 5.1.15 on 2026-06-12 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_renta_anticipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="renta",
            name="prenda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rentas",
                to="api.prenda",
            ),
        ),
    ]
