# Generated by Django 5.1.15 on 2026-06-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_renta_prenda_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="renta",
            name="ajustes",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
