# Generated by Django 5.1.15 on 2026-06-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_renta_ajustes"),
    ]

    operations = [
        migrations.AddField(
            model_name="renta",
            name="marca",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
