# Generated by Django 5.1.15 on 2026-06-12 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_renta_marca"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pieza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("saco", "Saco"),
                            ("chaleco", "Chaleco"),
                            ("pantalon", "Pantalón"),
                        ],
                        max_length=10,
                    ),
                ),
                ("color", models.CharField(max_length=120)),
                ("talla", models.CharField(max_length=80)),
                ("marca", models.CharField(blank=True, max_length=120)),
                ("detalles", models.CharField(blank=True, max_length=255)),
                ("codigo_old", models.CharField(blank=True, max_length=80)),
                ("codigo_new", models.CharField(blank=True, max_length=80)),
                (
                    "conjunto",
                    models.CharField(
                        blank=True,
                        help_text="Código de agrupación del traje original",
                        max_length=80,
                    ),
                ),
                (
                    "estatus",
                    models.CharField(
                        choices=[
                            ("rentado", "Rentado"),
                            ("disponible", "Disponible"),
                            ("mantenimiento", "Mantenimiento"),
                        ],
                        default="disponible",
                        max_length=20,
                    ),
                ),
                ("ubicacion", models.CharField(blank=True, max_length=120)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "pieza",
                "verbose_name_plural": "piezas",
                "ordering": ["tipo", "color", "talla"],
            },
        ),
        migrations.RemoveField(
            model_name="renta",
            name="prenda",
        ),
        migrations.AddField(
            model_name="renta",
            name="color_chaleco",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="renta",
            name="color_pantalon",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="renta",
            name="marca_chaleco",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="renta",
            name="marca_pantalon",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="renta",
            name="pieza_chaleco",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rentas_chaleco",
                to="api.pieza",
            ),
        ),
        migrations.AddField(
            model_name="renta",
            name="pieza_pantalon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rentas_pantalon",
                to="api.pieza",
            ),
        ),
        migrations.AddField(
            model_name="renta",
            name="pieza_saco",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rentas_saco",
                to="api.pieza",
            ),
        ),
    ]
