# Generated by Django 5.1.15 on 2026-06-12 23:22

from django.db import migrations, models


def migrar_estatus_devolucion(apps, schema_editor):
    Devolucion = apps.get_model("api", "Devolucion")
    Devolucion.objects.filter(estatus="salio").update(estatus="afuera")
    Devolucion.objects.filter(
        estatus__in=["listo_para_entregar", "sucio", "mojado", "en_ajustes"]
    ).update(estatus="regresado")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_piezas_inventario"),
    ]

    operations = [
        migrations.RunPython(migrar_estatus_devolucion, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="devolucion",
            name="estatus",
            field=models.CharField(
                choices=[
                    ("afuera", "Afuera"),
                    ("retrasado", "Retrasado"),
                    ("regresado", "Regresado"),
                ],
                max_length=24,
            ),
        ),
    ]
