# Generated by Django 5.1.15 on 2026-06-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_devolucion_estatus_simple"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorteDia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(unique=True)),
                (
                    "fondo_inicial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("cerrado", models.BooleanField(default=False)),
                ("cerrado_en", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "corte del día",
                "verbose_name_plural": "cortes del día",
                "ordering": ["-fecha"],
            },
        ),
    ]
