# Generated by Django 5.1.15 on 2026-06-13 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_configuracion_multa_por_dia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "linea_negocio",
                    models.CharField(
                        choices=[("trajes", "Trajes"), ("vestidos", "Vestidos")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "perfil de usuario",
                "verbose_name_plural": "perfiles de usuario",
            },
        ),
        migrations.AddField(
            model_name="configuracionsistema",
            name="linea_negocio",
            field=models.CharField(
                choices=[("trajes", "Trajes"), ("vestidos", "Vestidos")],
                default="trajes",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="cortedia",
            name="linea_negocio",
            field=models.CharField(
                choices=[("trajes", "Trajes"), ("vestidos", "Vestidos")],
                db_index=True,
                default="trajes",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pieza",
            name="linea_negocio",
            field=models.CharField(
                choices=[("trajes", "Trajes"), ("vestidos", "Vestidos")],
                db_index=True,
                default="trajes",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="prenda",
            name="linea_negocio",
            field=models.CharField(
                choices=[("trajes", "Trajes"), ("vestidos", "Vestidos")],
                db_index=True,
                default="trajes",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="renta",
            name="linea_negocio",
            field=models.CharField(
                choices=[("trajes", "Trajes"), ("vestidos", "Vestidos")],
                db_index=True,
                default="trajes",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transaccion",
            name="linea_negocio",
            field=models.CharField(
                choices=[("trajes", "Trajes"), ("vestidos", "Vestidos")],
                db_index=True,
                default="trajes",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cortedia",
            name="fecha",
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name="cortedia",
            constraint=models.UniqueConstraint(
                fields=("fecha", "linea_negocio"), name="unique_corte_fecha_linea"
            ),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
