# Generated by Django 5.1.15 on 2026-06-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_auth_linea_negocio"),
    ]

    operations = [
        migrations.AddField(
            model_name="pieza",
            name="precio_renta",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Precio de renta (vestidos / accesorios)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="pieza",
            name="precio_venta",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Precio de venta (vestidos / accesorios)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="pieza",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("saco", "Saco"),
                    ("chaleco", "Chaleco"),
                    ("pantalon", "Pantalón"),
                    ("vestido", "Vestido"),
                    ("accesorio", "Accesorio"),
                ],
                max_length=12,
            ),
        ),
    ]
