# Generated by Django 5.1.15 on 2026-06-19 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_renta_estatus_celda_colores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracionsistema",
            name="fondo_feria",
            field=models.DecimalField(
                decimal_places=2,
                default="2732.00",
                help_text="Fondo de feria (cambio) en caja, en MXN",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="devolucion",
            name="estatus",
            field=models.CharField(
                choices=[
                    ("revisar_salida", "Revisar si salió"),
                    ("afuera", "Afuera"),
                    ("retrasado", "Retrasado"),
                    ("regresado", "Regresado"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="pieza",
            name="precio_renta",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Precio de renta (vestidos)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="pieza",
            name="precio_venta",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Precio de venta (vestidos)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="renta",
            name="metodo_pago",
            field=models.CharField(
                choices=[
                    ("pesos", "Pesos"),
                    ("dlls", "DLLS"),
                    ("mixto", "Mixto"),
                    ("bbva", "BBVA"),
                    ("zelle", "Zelle"),
                ],
                default="pesos",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaccion",
            name="pago",
            field=models.CharField(
                choices=[
                    ("pesos", "Pesos"),
                    ("dlls", "DLLS"),
                    ("mixto", "Mixto"),
                    ("bbva", "BBVA"),
                    ("zelle", "Zelle"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Abono",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("pesos", "Pesos"),
                            ("dlls", "DLLS"),
                            ("mixto", "Mixto"),
                            ("bbva", "BBVA"),
                            ("zelle", "Zelle"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pago_efectivo_mxn",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "pago_efectivo_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "monto_mxn",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Equivalente en pesos para saldo y corte.",
                        max_digits=10,
                    ),
                ),
                (
                    "linea_negocio",
                    models.CharField(
                        choices=[("trajes", "Trajes"), ("vestidos", "Vestidos")],
                        db_index=True,
                        default="trajes",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "renta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abonos",
                        to="api.renta",
                    ),
                ),
            ],
            options={
                "verbose_name": "abono",
                "verbose_name_plural": "abonos",
                "ordering": ["creado_en", "id"],
            },
        ),
    ]
